import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import DashboardMenu from "@/components/menu";
import { Toaster } from "sonner";
import Navbar from "@/components/Navbar";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Portfolio Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Toaster />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <div className="grid grid-cols-12 h-screen gap-2">
          <aside className="col-span-2 bg-white shadow-lg">
            <DashboardMenu />
          </aside>
          <main className="col-span-10 p-6 overflow-y-auto">{children}</main>
        </div>
      </body>
    </html>
  );
}
